### PR TITLE
added !pokemon command

### PR DESCRIPTION
**Pull request by choogiesaur**
hope it works hahahah

### CODE REVIEW

**Comment by rob19780114** [comment]
:+1:

**Comment by rob19780114** [comment]
@choogiesaur Please fix your build, we badly need that feature! :)

**Comment by chauthai** [comment]
#14

**Comment by choogiesaur** [comment]
okay should work now? it was checking the number of commands which was 13...should be 14 now

**Comment by ScreenDriver** [comment]
Thank you very much :+1: 
Pull request merged.

**Pull request closed without merging**
